hotline-webring/hotline-webring

app/controllers/redirections_controller.rb
app/models/redirection.rb
config/routes.rb
db/migrate/20151110191852_create_redirections.rb
db/schema.rb
spec/controllers/redirections_controller_spec.rb
spec/factories.rb
spec/models/redirection_spec.rb
spec/spec_helper.rb

A redirection has:
* A slug (to find with)
* A url (to redirect to)
* A next (reference to another redirection)
* A previous (virtual reference to another redirection)
Using this, we can do `redirection.next.url` and `redirection.previous.url`
This is, as the title suggests a proof of concept. There's a bit of cleaning up (using the slug as a default find method, law of demeter in controller) to do. Lemme know what cha think.

Proof of Concept

---

app/assets/stylesheets/_landing-page.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/base/_grid-settings.scss
app/assets/stylesheets/base/_variables.scss
app/controllers/homes_controller.rb
app/views/homes/show.html.erb
app/views/layouts/application.html.erb
config/locales/en.yml
config/routes.rb

The white Helvetica on a pink background mimics the Hotline Bling album cover:
https://en.wikipedia.org/wiki/Hotline_Bling
It's the exact shade of pink from that cover.

Add a landing page explaining what this is

---

app/assets/stylesheets/_landing-page.scss
app/views/homes/show.html.erb

The video repeats "HOTLINE BLING" 6 times. (I counted.)

Repeat the header text, like the Drake video

---

app/assets/stylesheets/_landing-page.scss
app/assets/stylesheets/base/_typography.scss

Instead of only styling headers for the landing page, style them across the entire site.

Make header styling consistent everywhere

---

app/views/homes/show.html.erb

Some people might not know what a webring is, so let's explain their history, purpose, and utility.

Explain the concept of webrings

---

app/assets/stylesheets/_shirts.scss
app/assets/stylesheets/application.scss
app/views/homes/show.html.erb

Looks like this but moves right to left:

Create a marquee-style banner to advertise t-shirts

---

README.md

* We don't have to maintain documentation in two places (the README and the website)
* The explanation on the website is better than the one in the README

Refer interested parties to the website

---

app/views/homes/show.html.erb

Add a visitor counter

---

config/environments/staging.rb

Staging doesn't have SSL set up.

Don't force SSL on staging

---

Gemfile
Gemfile.lock

I looked through the [upgrading guide](https://github.com/teamcapybara/capybara/blob/master/UPGRADING.md) and I think we're good.

Upgrade to Capybara 3

---

db/schema.rb

There are NO changes to the actual database. This just uses Rails 5.2's new DB schema format.
@edwardloveall

Use new db/schema format

---

app/views/homes/show.html.erb

Deployed to staging: https://hotline-webring-staging.herokuapp.com

Encourage people to email us

---

app/assets/stylesheets/base/_lists.scss
app/views/homes/show.html.erb

Add a small guide for what sites are allowed

---

README.md
app/controllers/redirections_controller.rb
app/models/blacklisted_referrer.rb
app/models/block.rb
app/models/blocked_referrer.rb
db/migrate/20200703012614_rename_blacklisted_to_blocked.rb
db/schema.rb
spec/controllers/redirections_controller_spec.rb
spec/factories.rb
spec/models/block_spec.rb

In an effort to get away from racist terminology, this changes our use of Blacklist to Block:
* Blacklist -> Block
* BlacklistedReferrer -> BlockedReferrer
* referrer.blacklisted? -> referrer.blocked?

Rename Blacklist -> Block

---

app/models/missing_link_finder.rb
spec/models/missing_link_finder_spec.rb

Check for both next/prev links

---

app/controllers/redirections_controller.rb

We've had a few times where we wanted to see some evidence of redirection creation or failure, but heroku doesn't log headers (like the HTTP referrer).
I've added logging for when we do or do not have a referrer so we have a little more idea about what might have gone wrong in the redirection creation process.

Log headers on redirection failure

---

app/views/homes/show.html.erb

Don't allow commercial websites

---

app/controllers/redirections_controller.rb

Tagging it with the slug will make it easy to search in Papertrail.
Sample output from running it locally:
[asdfasdf] Redirection creation failed.
[asdfasdf] Referrer is BLANK!
[asdfasdf] Here are all of the HTTP headers:
[asdfasdf] {"HTTP_VERSION"=>"HTTP/1.1", "HTTP_HOST"=>"localhost:3000", "HTTP_USER_AGENT"=>"curl/7.64.1", "HTTP_ACCEPT"=>"*/*"}

Add logging when redirection creation fails

---

.github/workflows/heroku-deploy.yml

Automatically deploy to Heroku on merge

---

.github/workflows/heroku-deploy.yml

`if` should be at the job level, not the top level.
The most recent workflow failed on merge: https://github.com/hotline-webring/hotline-webring/actions/runs/673952019

Fix workflow syntax

---

.github/workflows/heroku-deploy.yml

I'm going to merge this so that it triggers exactly as it would normally.
The most recent workflow (for #315) worked for staging, but still didn't run for production: https://github.com/hotline-webring/hotline-webring/runs/2161451986?check_suite_focus=true

Add debugging output for GitHub actions

---

app/models/host_validator.rb
spec/models/host_validator_spec.rb

This also more-correctly blocks the IPs that we already blocked.
Fixes #319.

Block IPs in the range 192.168.*.*

---

app/views/homes/show.html.erb

It's hard to capture exactly what we're looking for on the 'ring and we've struggled to define it for years. We came up with "individual personality" as a way to describe what we're looking for on a website and we think it works well, so we're using it.

Rule clarification

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_variables.scss
app/assets/stylesheets/admin.scss
app/controllers/admin/redirections_controller.rb
app/views/admin/redirections/edit.html.erb
app/views/admin/redirections/index.html.erb
config/initializers/simple_form.rb
config/locales/simple_form.en.yml
config/routes.rb
spec/features/admin_edits_redirection_spec.rb

Allow editing URL in admin

---

Gemfile.lock

https://github.com/advisories/GHSA-wq4h-7r42-5hrr

Update Rack to fix a security vulnerability
