app/models/ring.rb
spec/models/ring_spec.rb

The `Ring` class takes care of breaking links, adding another redirection, and re-forming links to take into account the new entry.
It runs in a transaction so that if part of `Ring#link` fails, we're not left with junk data.
This should help with #5.

Easily add another link to the ring

---

db/migrate/20151111222648_remove_foreign_key.rb
db/schema.rb
db/seeds.rb
spec/controllers/redirections_controller_spec.rb
spec/factories.rb
spec/models/redirection_spec.rb
spec/models/ring_spec.rb
spec/support/database_cleaner.rb

The foreign key constraint on the `next_id` column meant that we can't insert the first record, because any ID we put on next_id won't be a valid foreign key (since there's nothing in the table).
This migration removes that foreign key constraint so that we can insert the first few records and kickstart the ring.
All specs are passing.

Remove foreign key constraint

---

app/models/ring.rb
db/seeds.rb
spec/controllers/redirections_controller_spec.rb
spec/factories.rb
spec/models/redirection_spec.rb
spec/models/ring_spec.rb

Previously we were doing some, uh, interesting stuff around newest/oldest Redirections, which assumed that the newest redirection links to the oldest one.  That's not necessarily true.
Now we:
* Grab the first Redirection (`@from_redirection`)
* Grab the Redirection that that Redirection points to (`@to_redirection`)
* Break the link between them
* Insert a new redirection between them
This ensures that we're breaking a link that definitely exists, instead of breaking a link that we assume (based on creation time) exists.
This commit also refactors the tests to use the existing gabe/edward Redirections that are created via DB seeds.

Always break the ring at the first element

---

app/controllers/redirections_controller.rb
app/models/ring.rb
spec/controllers/redirections_controller_spec.rb

When we receive a request for `/new-slug/next` or `/new-slug/previous`, we:
* check if there's an entry for `new-slug`
* if there isn't, we add it to the ring
* redirect to the next/previous URL for `new-slug`

Auto-create redirections

---

app/controllers/redirections_controller.rb
app/services/redirection_creation.rb
spec/controllers/redirections_controller_spec.rb
spec/services/redirection_creation_spec.rb

RedirectionCreation handles creating (or not creating!) a new Redirection based on a slug and referrer. It also links the new redirection into the ring.
Since we handle edge cases (like a blank referrer) at the RedirectionCreation unit test level, the controller specs can now be correspondingly simpler.

Extract a RedirectionCreation service

---

app/assets/stylesheets/base/_typography.scss
app/assets/stylesheets/base/_variables.scss
app/controllers/homes_controller.rb
app/models/redirection.rb
app/views/homes/show.html.erb
app/views/redirections/_redirection.html.erb
lib/tasks/dev.rake
spec/models/redirection_spec.rb

This adds the contents of the current webring on the homepage so people A) have a place to point and say "Hey that's me!" and for potential users to see what slugs already exist.
It looks like this:

Homepage links & slugs

---

app/views/homes/show.html.erb
spec/features/user_visits_homepage_spec.rb

In a previous (now squashed) commit, I had a helper method for
`redirections` on the homepage to avoid an ivar. However, I changed
back to an ivar in the `HomesController` but not in the view. The app
crashed on the homepage.
This is now tested for.

Fix regression on homepage

---

app/views/redirections/_redirection.html.erb
spec/features/user_visits_homepage_spec.rb

Previously we weren't providing a URL to `link_to` so it was linking to the hotlinewebring.club site.

Link to the sites on the homepage

---

app/assets/stylesheets/_landing-page.scss
app/assets/stylesheets/base/_grid-settings.scss
app/views/homes/show.html.erb

People should be able to use the webring right away.
There's some SCSS weirdness with `shift` and `max-width` to make the body text about as narrow as the "HOTLINE WEBRING" without the arrows, while making `$max-width` large enough to let the layout to accommodate the arrows. I welcome feedback.

Add webring links to the landing page

---

app/assets/stylesheets/_mobile.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/base/_base.scss
app/assets/stylesheets/base/_grid-settings.scss

On mobile screens:
* Hide the giant video
* Use a smaller header text so each "HOTLINE WEBRING" header is on its own line instead of breaking over multiple lines
I tested it with Safari's (extremely handy) Responsive Design Mode, and the site looks good on everything from an iPhone 4S to an iPad Pro.

Mobile-ify the layout

---

app/assets/stylesheets/_landing-page.scss
app/assets/stylesheets/_mobile.scss
app/assets/stylesheets/base/_base.scss
app/controllers/redirections_controller.rb
app/views/homes/show.html.erb
app/views/pages/localhost.html.erb
spec/controllers/redirections_controller_spec.rb

When people click links on their site running on `http://localhost:3000`, we were adding `http://localhost` to the webring.
Now we don't add localhost requests to the webring, and we provide a helpful explanation of what's going on.

Ignore people arriving from localhost

---

spec/features/user_visits_homepage_spec.rb

I always forget, but capybara has a `has_link` or `have_link` matcher
that can be used to test if a link is on a page:
http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Matchers#has_link%3F-instance_method
This cleans up a test for us nicely.

Use has_link matcher to test homepage

---

Gemfile
Gemfile.lock
circle.yml

With this formatter, Circle should pretty-print our failures. We need a custom spec command because otherwise Circle only runs RSpec, while `bundle exec rake` runs `rake bundle:audit` as well.
https://circleci.com/docs/test-metadata#automatic-test-metadata-collection
I also changed the specs so we can see how failures look now. I'll remove the failures before merging.

Add RSpec formatter for Circle CI

---

app/controllers/redirections_controller.rb
app/models/host_validator.rb
app/views/pages/localhost.html.erb
spec/controllers/redirections_controller_spec.rb
spec/models/host_validator_spec.rb

Previously we were only checking for referrers from `localhost`. Now we check for:
* `localhost` (like `http://localhost:3000`)
* `127.0.0.1` (like `http://127.0.0.1:3000`)
* `*.dev` (like `http://example.dev`)
Introduce a `HostValidator` model to cover the new logic.

Ignore a wider variety of local requests

---

config/environments/production.rb

Now that Cloudflare gives us SSL, we should force people to use it instead of plain ol' HTTP.

Force SSL in production (and staging)

---

app/views/homes/show.html.erb

* When an HTTPS site links to the HTTP version of Hotline Webring, it won't send a Referer header
* Hotline Webring relies on the Referer header to know which site to add to the ring
* Linking to the HTTPS version of Hotline Webring ensures that we always get a Referer header, whether the linking site is using HTTPS or not

Recommend secure webring links

---

app/views/feeds/show.atom.builder
spec/requests/feed_requests_spec.rb

When a new Redirection is added to the webring, the first Redirection in the ring points to it. This changes that first Redirection's `updated_at` value.
In the atom feed, we were using `updated_at` to say when that entry was updated. While that's semantic, it would cause the first Redirection to continue to pop up in atom feeds because it looked like there was new information. No longer!
We now use `created_at` in that field, because for the purposes of the feed, we only want to see each Redirection when it's added, not "updated".

Use created_at in atom feed entries

---

app/assets/stylesheets/_landing-page.scss
app/views/homes/show.html.erb

Remove the underlines on the arrow links.

Only repeat the site's name once in the header

---

Gemfile.lock
spec/features/user_visits_localhost_page_spec.rb

On production, starting the server immediately fails with this error:
undefined method `hide_action' for HighVoltage::PagesController:Class
This is because `hide_action` was removed from controllers in Rails 5.
This error does _not_ occur in development or test because those environments have `config.eager_load` set to `false`, so the `HighVoltage::PagesController` code is never loaded, and thus doesn't fail.
The test added in this commit exercises the `HighVoltage::PagesController` code, and fails without upgrading high_voltage.
To fix this issue, upgrade to high_voltage 3.0.0, which supports Rails 5: https://github.com/thoughtbot/high_voltage/blob/master/NEWS.md

Add a test for visiting a High Voltage page

---

README.md
app/models/redirection.rb
spec/models/redirection_spec.rb

I know, I know: who would want such a thing?!
The `unlink` method runs in a transaction so that removing a Redirection and re-linking its neighbors is an atomic operation. In other words, we can't remove a Redirection, run into an error, and then leave a hole in the ring.

Add a method to remove a site from the webring

---

app/views/homes/show.html.erb

The external link was broken. To prevent this from happening again, self-host the spaniel.

Self-host the bitmap of a Clumber Spaniel

---

lib/tasks/link-audit.rake

This taks should help us to maintenance on the webring's members. It
checks each redirection for proper next and previous links. It downloads
the page and scans the raw html for the proper urls. It doesn't check
for actual links because some sites (looking at you @jnutting) don't use
normal `<a href="...">` links.
This also found other issues while I was testing it like sites that have
migrated to https because the html only returned the redirection (and
therefore didn't include the links).

Add link_audit rake task

---

lib/tasks/link-audit.rake

Some sites now have https where before they only used http. Our link
audit task was not following redirects, and therefore would get to a
page that said "moved permanantly" and did not have the normal HLWR
links on it, so it would fail the link audit.

Follow redirections for link_audit task

---

app/views/homes/show.html.erb

The counter loads over insecure HTTP and is blocked.
This fixes #53.

Remove broken counter

---

Gemfile
config/database.yml
config/environments/production.rb
config/environments/staging.rb
config/newrelic.yml
config/secrets.yml

`RAILS_ENV` is set to `production` on the staging and production environments (as recommended by Heroku).
Since both staging and production environments load `production.rb`, we introduce a `USE_SSL` environment variable that will only be enabled in the production environment. Staging does not have SSL set up.
I already set `USE_SSL` on production:
$ heroku config:get USE_SSL -a hotline-webring-production
true

Remove staging environment

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

It no longer installs on macOS Sierra (the [wiki] recommends checking out an old version of Homebrew to install Qt5.5), making it difficult to run tests on a new computer.
In addition, we don't have any Javascript tests.
Thus, the easiest thing is just to not use capybara-webkit.
[wiki]: https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit

Remove capybara-webkit

---

bin/rails
bin/rake

Running any rails command (like `rails server`) showed this warning:
```
Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.
An Array ({"GEM_PATH"=>["/Users/gabe/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0", "/Users/gabe/.gem/ruby/2.4.0"]}) was passed in from bin/rails:3:in `load'
```
To fix the warning, I ran this command:
```
rails app:update:bin
```
@edwardloveall

Regenerate new-style binstubs for Rails

---

Gemfile.lock

Our apps are on the deprecated `cedar-14` stack.
In order to upgrade to the new `heroku-18` stack, we need to upgrade Puma, since version 3.6.0 fails to build on `heroku-18`.
(I confirmed that this works on `heroku-18` by deploying to staging.)
More about Heroku stacks here: https://devcenter.heroku.com/articles/stack

Update Puma for heroku-18 stack

---

.circleci/config.yml

You can see that the first commit, which removed `db:test:prepare` (which we do need), has a bad Circle CI output and doesn't summarize the failing tests at the top: https://circleci.com/gh/gabebw/hotline-webring/280
However, the latest commit, which stores test results correctly, does summarize the failing tests: https://circleci.com/gh/gabebw/hotline-webring/283
(I will remove the failing commit once this PR is approved.)
Using `path: $CIRCLE_TEST_REPORTS` made it look at a directory literally called `$CIRCLE_TEST_REPORTS`. It didn't use the value of the environment variable. Therefore, I now hardcode it as a string.
According to  https://circleci.com/docs/2.0/configuration-reference/#store_test_results, we should store it to `test-results/rspec/results.xml`, and save `test-results`, so …

Correctly show failing tests

---

Gemfile
Gemfile.lock
lib/tasks/dev.rake
spec/factories.rb
spec/support/factory_bot.rb
spec/support/factory_girl.rb

It was renamed in version 4.8.2: https://github.com/thoughtbot/factory_bot/blob/master/NEWS
This also fixes a small warning from the new FactoryBot version:
```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot
5.0. Please use dynamic attributes instead by wrapping the attribute
value in a block:
next_id { -1 }
```

FactoryGirl is now named FactoryBot

---

.circleci/config.yml

Previously, builds would start a new cache in these cases:
* when building a new branch for the first time (since the branch name changed)
* when `Gemfile.lock` changes
However, the cache only saves Gemfile-related paths. Therefore, the cache is OK to use for new branches, as long as the `Gemfile.lock` is the same.
After this commit, a build can use a different branch's cache as long as they're using the same `Gemfile.lock`. This should significantly speed up the first build on new branches.
I've also changed the name of the cache to include `gemfile`, so that if we add other caches in the future, it doesn't get confusing.

Use a CircleCI cache across different branches

---

Gemfile
Gemfile.lock

In PR #105, we removed Capybara because it's not in our Gemfile explicitly and #105 removed the last gem depending on Capybara.
Because of this, none of our feature specs run:
```
1) User visits homepage sees list of redirections
```
Therefore, bring back Capybara to run feature specs.

Bring back Capybara gem so feature specs run

---

README.md
bin/setup

`heroku local` has been the preferred solution for a while now.
The `bin/setup` script now requires you to install `heroku`.

Prefer `heroku local` to Foreman

---

app/services/redirection_creation.rb
db/migrate/20181220204317_add_original_url_to_redirection.rb
db/schema.rb
db/seeds.rb
spec/factories.rb
spec/services/redirection_creation_spec.rb

We currently store only the hostname of the HTTP referrer (e.g. `gabebw.com/posts/2018/whatever` is saved as just `gabebw.com`).
This is a problem for pages on free sites, where the homepage for a given user is not the root hostname but a subdirectory (e.g. `freepages.rootsweb.com/~gabebw`).
This is not a fix for issue #58, but it does allow us to manually fix that issue if it recurs.

Store the whole original referring URL

---

config/environments/production.rb

The `Rack::Timeout.timeout=` method no longer exists. It was removed in rack-timeout 0.5, which we upgraded to in commit 003248f9.
Relevant Suspenders PR: https://github.com/thoughtbot/suspenders/pull/920

Configure rack-timeout with env variable

---

app/assets/stylesheets/_mobile.scss
app/views/redirections/_redirection.html.erb

* Word-wrap the URLs so they don't extend off the side of the screen
* Add a bit more padding at the top of the site on smaller screens
Note the lack of top padding and the way the URLs extend off the side of the screen.
There's now more padding at the top, and the URLs wrap inside the table.

Make the site look a bit better on mobile

---

lib/tasks/link-audit.rake

When trying to run `Net::HTTP.get_response` on a website that is not online (like http://alexfox.me, in our webring), it throws a `SocketError`.
Now we rescue that error and print an error message, rather than crashing the audit.
I also improved the redirection detection to now support `Net::HTTPMovedPermanently` (a 301 Redirect) as well.

Rescue errors and detect redirects in link audit

---

lib/tasks/link-audit.rake

As you can see by doing `curl https://alexeyzabelin.com`, this HTML works just fine in the browser:
```
<a href="https:&#x2F;&#x2F;hotlinewebring.club&#x2F;alexey&#x2F;next">next</a>
```
`&#x2F` is the hexadecimal encoding of `/`.
Therefore, it should "count" as a real HLWR link.
I have updated the link checker to allow both versions of the forward slash, regular and encoded.

Allow encoded slashes

---

app/views/layouts/application.html.erb

An "unfurl" is what Slack calls its link previews: https://api.slack.com/docs/message-link-unfurling#classic_unfurling
Fixes #176
Here's what it looks like in [Twitter's card validator](https://cards-dev.twitter.com/validator):
And in Slack:

Make the website unfurl in Slack and Twitter

---

Gemfile
Gemfile.lock

When deploying the Rails 6 app to Heroku, I saw this warning:
>DEPRECATION WARNING: Including LoggerSilence is deprecated and will be removed in Rails 6.1. Please use `ActiveSupport::LoggerSilence` instead
The warning is apparently coming from the rails_stdout_logging gem, according to this issue: https://github.com/heroku/rails_12factor/issues/33.
Based on the README (https://github.com/heroku/rails_12factor#migrating-to-rails-5), we already do everything that rails_stdout_logging would do for us, manually (see `config/enviroments/production.rb` for our `RAILS_SERVE_STATIC_FILES`- and `RAILS_LOG_TO_STDOUT`-related settings).
Thus, we can just remove the gem.
https://github.com/gabebw/hotline-webring/blob/96056887cff05a8ccecfd99c4865da22eccf1e6c/config/environments/production.rb#L6 …

Remove unneeded rails_stdout_logging gem

---

README.md
app/controllers/redirections_controller.rb
app/models/blacklist.rb
app/models/blacklisted_referrer.rb
db/migrate/20200312175018_create_blacklisted_referrers.rb
db/schema.rb
spec/controllers/redirections_controller_spec.rb
spec/factories.rb
spec/models/blacklist_spec.rb

The expected process for blacklisting:
* We manually add the host as a BlacklistedReferrer
* We manually unlink the offending Redirection
After that, whenever someone clicks "next" or "previous" from the offending site, they will be taken to the first Redirection and the site will _not_ be added to the ring.
Mostly fixes #206. Later, we'll probably want a specific page saying "you can't join" as detailed in #206. This PR just silently won't let them join.

Allow blacklisting certain URLs

---

app/models/redirection.rb
spec/controllers/redirections_controller_spec.rb
spec/models/redirection_spec.rb

When creating a new Redirection, this will normalize the URL by removing the protocol (HTTP/S) and any `www.` subdomain. So this:
```
https://www.foo.com/something?else=1
```
becomes this:
```
foo.com/something?else=1
```
Then we compare that normalized URL against the normalized URL of every other redirection, and mark the new record as invalid if there's a match.
-------------
This was prompted by a Redirection being added for `http://hotlinewebring.club`
when HLWR itself has `https://hotlinewebring.club`.
My big concern is:
* Running Ruby code every time we touch a Redirection is inefficient. Should we store the normalized URL in a field on the Redirection and re-calculate it whenever it's created/updated? Does it matter, given the number of records we're talking about?

Disallow creating different slugs with similar URLs

---

bin/rspec
bin/spring

`bin/spring` was using `Gem.paths=` which printed this warning whenever `bin/rspec` (which uses Spring) ran:
>Array values in the parameter to `Gem.paths=` are deprecated.
Now it uses different code and does not print a warning.

Use newer Spring binstubs to avoid warning

---

app/models/missing_link_finder.rb
lib/tasks/link-audit.rake
spec/models/missing_link_finder_spec.rb

* Just like before, if there's a `SocketError`, indicate that the website is completely offline
* If there is any other kind of error (`StandardError`), print the error message
The certificate for https://irongeek.net expired and the `rake link_audit` task crashed when it got to it. Now it prints the error and keeps going.
To accommodate showing more information, the `MissingLinkFinder` now sends more information back to the link audit task, including a `status` plus information relating to that status.

Make the link audit task more resilient

---

Gemfile
app/models/missing_link_finder.rb

It broke the whole website (now rolled back) because we try to load capybara-mechanize when we preload all the classes.
I tested this branch on staging, so it definitely works now.

Make capybara-mechanize available in production

---

app/models/redirection.rb
app/models/uri_comparison.rb
app/services/redirection_creation.rb
spec/models/redirection_spec.rb

Someone created a Redirection for "hotlinewebring.club/" with a trailing slash. Let's prevent that in the future.

Ignore trailing slash when comparing URLs

---

.circleci/config.yml
app/models/block.rb
config/database.yml
spec/models/block_spec.rb

Previously, when blocking `evil.com/subpath`, it would block all of `evil.com`, because our SQL condition was switched.
It was also not case-insensitive.
This fixes both issues, and adds tests.

Limit blocks so they don't affect the whole domain

---

db/migrate/20151103053545_create_delayed_jobs.rb
db/migrate/20151110191852_create_redirections.rb
db/migrate/20151111222648_remove_foreign_key.rb
db/migrate/20151217165101_remove_delayed_jobs.rb
db/schema.rb

Rails 7 will throw an error about unversioned migrations:
Directly inheriting from ActiveRecord::Migration is not supported.
Please specify the Active Record release the migration was written
for.

Version all old ActiveRecord migration classes

---

config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/new_framework_defaults_6_0.rb
spec/support/action_mailer.rb

We can't remove the gems since `rails` pulls them in, but we can avoid loading them in the first place.

Remove everything about ActionMailer and ActiveJob

---

config.ru

I don't think the `load_server` change changes anything for the app now, but calling `load_server` ensures we run the Railtie `server` hook, which other gems might use.

Make `config.ru` match Rails 7

---

Gemfile.lock

We get this warning when running tests otherwise:
> This library has only been tested up to Ruby 2.x, but you are running with Regexp::Syntax::V3_0_3 (feature set of V2_6_3)

Update `regexp_parser` gem for Ruby 3

---

.sample.env
app/assets/stylesheets/_flashes.scss
app/assets/stylesheets/_variables.scss
app/assets/stylesheets/admin.scss
app/controllers/admin/blocks_controller.rb
app/controllers/admin/redirections_controller.rb
app/controllers/admin_controller.rb
app/models/blocked_referrer.rb
app/views/admin/redirections/index.html.erb
app/views/layouts/admin.html.erb
config/initializers/assets.rb
config/routes.rb
spec/features/admin_blocks_a_redirection_spec.rb
spec/features/admin_views_redirections_spec.rb
spec/models/block_spec.rb
spec/models/blocked_referrer_spec.rb
spec/support/features/admin.rb

This will let us make quick changes without opening up the Heroku console.
It is responsive, so we can also do it on our phones.
To see it, go to https://hotline-webring-staging.herokuapp.com/admin and use the username/password that I will tell you.

Add an admin panel

---

app/controllers/redirections_controller.rb
spec/controllers/redirections_controller_spec.rb

If the Redirection is already in the webring, then redirect to it instead of to `Redirection.first`.
This fixes a bug with the Redirection for HLWR itself: we blocked the `"hotlinewebring.club"` URL so that nobody can add it as their own site, but because it's blocked, it doesn't redirect to its own next/previous links.
This change also means that when we block but do not unlink a site, then clicking on its links will redirect to its actual next/previous links instead of `Redirection.first`, which is fine. Blocked sites cannot be added to the ring, but if they're already in, then they work normally.

Redirect to an existing blocked Redirection

---

app/assets/stylesheets/_pages.scss
app/controllers/redirections_controller.rb
app/views/homes/show.html.erb
spec/controllers/redirections_controller_spec.rb
spec/features/admin_blocks_a_redirection_spec.rb

We've been getting a lot of sites that aren't valid. Some seem like spam, some seem like bugs, but there are a lot of them. This makes it impossible to join automatically and adds instructions to contact us if a site would like to join.

Disable redirection creation

---

app/assets/stylesheets/_pages.scss
app/controllers/redirections_controller.rb
app/views/homes/show.html.erb
public/robots.txt
spec/controllers/redirections_controller_spec.rb
spec/features/admin_blocks_a_redirection_spec.rb

All of the user agents (`HTTP_USER_AGENT`) for the recent flood of spam requests are crawlers:
* Applebot
* SemrushBot
* PetalBot
* DataForSeoBot
Here's an example line from the logs, anonymized:
```
[SLUG_GOES_HERE] {"HTTP_VERSION"=>"HTTP/1.1", "HTTP_HOST"=>"hotlinewebring.club", "HTTP_CONNECTION"=>"close", "HTTP_USER_AGENT"=>"Mozilla/5.0 (compatible; DataForSeoBot/1.0; +https://dataforseo.com/dataforseo-bot)", "HTTP_ACCEPT_ENCODING"=>"gzip, deflate, br", "HTTP_UPGRADE_INSECURE_REQUESTS"=>"1", "HTTP_X_REQUEST_ID"=>"117ec039-a786-4a9a-96f4-464fb6397ba9", "HTTP_X_FORWARDED_FOR"=>"142.132.248.181", "HTTP_X_FORWARDED_PROTO"=>"https", "HTTP_X_FORWARDED_PORT"=>"443", "HTTP_VIA"=>"1.1 vegur", "HTTP_CONNE→
```
My guess is that these crawlers archived the links on people's websites (e.g. …

Block search engine crawler bots

---

app/views/feeds/show.atom.builder
spec/factories.rb
spec/requests/feed_requests_spec.rb

This will make it easier for us to find the links in Slack.

Display *original* URL in RSS feed

---

lib/tasks/link-audit.rake

We have a lot of sites, and some of them are not really "in" the webring any more:
* the site is no longer online
* the site is online but has an SSL certificate error
* the `next` and/or `previous` links to other HLWR sites are missing
* and so on.
We can't keep up with every single possible error, but we also want to keep the webring as a connected ring of valid sites. When one of the sites in the ring is invalid, it breaks the ring.
So let's do the easiest thing possible: if `rake link_audit` detects any error at all, it removes that site from the webring (**without blocking them**). If someone wants to rejoin, they can do so very easily.
https://github.com/hotline-webring/hotline-webring/issues/385

Unlink sites that fail `drake link_audit`

---

app/views/homes/show.html.erb

Some people will put their links on a page that's pretty difficult to find. That's fine, but they should know that we will find it and redirect people there. This encourages them to put the links on a cool page.

Note about what page to put your links on

---

app/views/homes/show.html.erb
app/views/layouts/application.html.erb

The meta description shows up in e.g. Slack unfurls.

Do not encourage people to join in the `<meta>` description if it's closed

---

Gemfile
Gemfile.lock
app/assets/stylesheets/admin.scss
app/controllers/admin/redirections_controller.rb
app/controllers/redirections_controller.rb
app/models/redirection.rb
app/views/admin/redirections/index.html.erb
db/migrate/20250627212857_add_last_seen_to_redirections.rb
db/schema.rb
spec/features/admin_views_redirections_spec.rb
spec/features/user_visits_a_redirection_link_spec.rb
spec/models/redirection_spec.rb
spec/rails_helper.rb

In order to help track sites that have gone defunct, we can track the last time they were "seen" by updating a `last_seen_at` column every time someone clicks their next or previous link.
I also updated the admin interface to actually be a grid instead of each line being it's own grid. Now all the columns line up.

Add "Last seen" column to admin interface
